# https://taskfile.dev

version: '3'

tasks:
  macos:
    cmds:
      - mkdir -p build/mac/
      - go build -v -o build/mac/getapp ./cmd/getapp

  build:
    cmds:
      - mkdir -p build/bin/
      - docker run -v `pwd`/:/go/src/getapp -w /go/src/getapp -e "VERSION=0.0.1" -i golang:1.21.1 /bin/sh -c "GOOS=linux GOARCH=amd64 go build -v -o build/bin/getapp -ldflags '-v -w -s -linkmode auto -extldflags \"-static\" -X main.Version=0.0.1' ./cmd/getapp"

  deploy:
    deps: [build]
    cmds:
      - task: deploy-instance
        vars:
          SERVER: getapp01
      - task: deploy-instance
        vars:
          SERVER: getapp02

  deploy-instance:
    internal: true
    cmds:
      - sup {{ .SERVER }} stop
      - scp ./build/bin/getapp {{ .SERVER }}:/opt/getapp/bin/
      - scp ./configs/prod.yml {{ .SERVER }}:/opt/getapp/configs/
      - scp ./configs/base.yml {{ .SERVER }}:/opt/getapp/configs/
      - scp ./templates/users/choose.gohtml {{ .SERVER }}:/opt/getapp/templates/users/
      - scp ./templates/users/mail/login.gohtml {{ .SERVER }}:/opt/getapp/templates/users/mail/
      - scp ./templates/users/mail/send.gohtml {{ .SERVER }}:/opt/getapp/templates/users/mail/
      - scp ./templates/users/mail/success.gohtml {{ .SERVER }}:/opt/getapp/templates/users/mail/
      - scp ./templates/users/vkontakte/login.gohtml {{ .SERVER }}:/opt/getapp/templates/users/vkontakte/
      - scp ./templates/billing/base.gohtml {{ .SERVER }}:/opt/getapp/templates/billing/
      - scp ./templates/billing/purchase.gohtml {{ .SERVER }}:/opt/getapp/templates/billing/
      - scp ./templates/billing/success.gohtml {{ .SERVER }}:/opt/getapp/templates/billing/
      - scp ./templates/admin/home.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - scp ./templates/admin/conversions.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - scp ./templates/admin/impressions.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - scp ./templates/admin/ecpms.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - scp ./templates/admin/payments.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - scp ./templates/admin/subscriptions.gohtml {{ .SERVER }}:/opt/getapp/templates/admin/
      - sup {{ .SERVER }} start
