application:
  logger:
    level: info
    encoding: json
    colored: false
    tags:

  database:
    host: db.example.ru
    user: db
    password: example
    database: example

  mail:
    password: example
    out: "smtp.yandex.ru"
    in: "imap.yandex.ru"
    port: 25
    username: "example@example.store"

  server:
    address: :3333

modules:
  billing:
    active: true
  boosty:
    active: true
  admin:
    username: admin
    password: admin
