### stats
#GET https://target.my.com/api/v2/statistics/geo/pads/hour.json?id=1812360&date_from=2024-01-13&date_to=2024-01-15
GET https://target.my.com/api/v2/statistics/geo/pads/hour.json?id=2134141&date_from=2024-02-16&date_to=2024-02-17
Authorization: Bearer {{mytarget}}
